### ISSUE TITLE
lunching error 

### ISSUE THREAD

**Issue by mohamed33-cpc** [martimy/flowmanager#10]
![Capture](https://user-images.githubusercontent.com/93062952/141401267-e45fd841-a092-4274-ae62-ead7735fbab5.JPG)

hello dear, 
I'm trying to lunch your app and I got this error, can you help plz. another question , I want to use it with Ryu controller should I clone it in the same folder with the controller or at user mode? . THANKS IN ADVANCE

**Comment by martimy** [comment]
Hi, 
It looks like the app cannot create flwmgr.log file due to permissions. Maybe you cloned the repo as root. Make sure the app has the write permissions.
For the 2nd question, you should clone the flowmanager in a separate folder than Ryu.
