### ISSUE TITLE
no switch or host icons showing in topology

### ISSUE THREAD

**Issue by LaochMumhain** [martimy/flowmanager#2]
**Is your feature request related to a problem? Please describe.**

```
ryu@ryu-mn:~$ ryu-manager --observe-links --app-lists  ~/flowmanager/flowmanager.py ryu.app.simple_switch_13
loading app /home/ryu/flowmanager/flowmanager.py
('You are using Python ', sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0))
loading app ryu.app.simple_switch_13
loading app ryu.topology.switches
loading app ryu.controller.ofp_handler
instantiating app None of DPSet
creating context dpset
creating context wsgi
instantiating app /home/ryu/flowmanager/flowmanager.py of FlowManager
instantiating app ryu.app.simple_switch_13 of SimpleSwitch13
instantiating app ryu.topology.switches of Switches
instantiating app ryu.controller.ofp_handler of OFPHandler
(2549) wsgi starting up on http://0.0.0.0:8080


ryu@ryu-mn:~$ sudo mn --topo tree,depth=2,fanout=2 --switch ovsk --controller=remote,ip=127.0.0.1,port=6653 --mac
*** Creating network
*** Adding controller
*** Adding hosts:
h1 h2 h3 h4 
*** Adding switches:
s1 s2 s3 
*** Adding links:
(s1, s2) (s1, s3) (s2, h1) (s2, h2) (s3, h3) (s3, h4) 
*** Configuring hosts
h1 h2 h3 h4 
*** Starting controller
c0 
*** Starting 3 switches
s1 s2 s3 ...
*** Starting CLI:
mininet> 
```
Only the links and circles for the switch interfaces appear in the topology. I expected to see the switches and hosts as green icons.

**Describe the solution you'd like**

Visible switches and host icons.
![flowmanager](https://user-images.githubusercontent.com/12687178/49818992-50085080-fd85-11e8-86c5-e0ef2e0444f3.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by martimy** [comment]
Icons do not show when using Firefox. Use Chrome instead.

**Comment by chitsukhin** [comment]
In Flow Summary, which packet are count in the PACKET COUNT field??? Packet-in??
![image](https://user-images.githubusercontent.com/51238327/65298864-1aee2180-db93-11e9-95a3-aee24add3579.png)

**Comment by martimy** [comment]
The Flow Summary table shows the total numbers of 1) packets that passed through the switch, 2) flow entries, and 3) bytes in all packets. As of now, there is no single location in FlowManager where you can find the number of PACKET_IN packets received by the controller. You can find that by adding the packet counts of all the flow entries that have the action "OUTPUT:CONTROLLER".
