### ISSUE TITLE
how to count packet-in message ??/

### ISSUE THREAD

**Issue by chitsukhin** [martimy/flowmanager#3]
In Flow Summary, which packet are count in the PACKET COUNT field??? Packet-in??
![image](https://user-images.githubusercontent.com/51238327/65309982-3d903280-dbb3-11e9-99e0-200b3ae79dff.png)

**Comment by martimy** [comment]
The Flow Summary table shows the total numbers of 1) packets that passed through the switch, 2) flow entries, and 3) bytes in all packets. As of now, there is no single location in FlowManager where you can find the number of PACKET_IN packets received by the controller. You can find that by adding the packet counts of all the flow entries that have the action "OUTPUT:CONTROLLER".
