### ISSUE TITLE
Port statistics in Match Field

### ISSUE THREAD

**Issue by amitnayyer** [martimy/flowmanager#4]
Firstly, let me clarify that I m a newbie to FlowManager. I want to add a flow rule that will happen only when the traffic at a particular port is below a specific integer. I check all the fields in Match Field tab under Flow Control tab but did not find anything suitable to my requirements. Is it possible or not ? in any way. Please help me out.

**Comment by martimy** [comment]
It is not possible to have a match basted on traffic amount. What you may do is to write an application that requests the byte/packet counters from the switch regularly then send a flow entry that include the desired action.
