### ISSUE TITLE
Log Message Page did not work

### ISSUE THREAD

**Issue by c1x1x00xxPentium** [martimy/flowmanager#6]
Dear Mr. Maen Artimy,

**Bug Report : Log Message Page not showing any log**
I was trying to looking for log messages about what happen in my topology (ex. Mininet Topology), such as about Packet-In or Packet-Out messages. It seem your current code is not work well yet.
Could you please fix a few lines of code about "Log Message Page"?

**Feature request : Snort Alert Log Messages**
Can I know, is it possible to create a new page for showing Snort (IDS) Alert Message if I using it for detect an intrusion on my topology ? 
Could you give me a advice / suggestion how to do it ?

Thank You

**Comment by martimy** [comment]
Hi,
The FlowManger logs only events related to the controller (e.g switch connect/disconnect). Other logs should be created by the application (see https://github.com/faucetsdn/ryu/blob/master/ryu/app/simple_switch_13.py) . This applies to both of your issues. If I miss understood, you could send me your application and I'll see if I can help.

**Comment by c1x1x00xxPentium** [comment]
Log Message Page (Release Version 0.3.2)
![05](https://user-images.githubusercontent.com/45236352/123368011-30cd1980-d5a5-11eb-9017-8bbf931adb0e.png)

Error Message : 
`Traceback (most recent call last):`
`  File "/usr/lib/python3/dist-packages/ryu/base/app_manager.py", line 290, in _event_loop`
`    handler(ev)`
`  File "/home/guest/Documents/Flowmanager-RYU/flowmanager-0.3.2/flowmanager.py", line 765, in packet_in_handler`
`    self.rpc_broadcall("log", json.dumps(log))`
`  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps`
`    return _default_encoder.encode(obj)`
`  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode`
`    chunks = self.iterencode(o, _one_shot=True)`
`  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode`
`    return _iterencode(o, 0)`
`  File "/usr/lib/python3.8/json/encoder.py", line 179, in default`
`    raise TypeError(f'Object of type {o.__class__.__name__} '`
`TypeError: Object of type map is not JSON serializable`

Another Error form "Topology Page":
After starting my topology, the page showing like this and I can not do `pingall` command on Mininet terminal.
![123368491-1b0c2400-d5a6-11eb-9a64-b6c640a46e54](https://user-images.githubusercontent.com/45236352/123452868-0ca32400-d609-11eb-9420-94b9833ba547.png)
![07](https://user-images.githubusercontent.com/45236352/123368516-23fcf580-d5a6-11eb-9f72-fcbfd9a246bd.png)


Log Message Page (Release Version 0.2.0)
In this version the Log Message Page is working well.
![02](https://user-images.githubusercontent.com/45236352/123368032-3aef1800-d5a5-11eb-9aeb-f23aa1ac88ba.png)

-----------------------------
And about feature request maybe like this :
Can you give me an advice , Sir ?
![01](https://user-images.githubusercontent.com/45236352/123368206-91f4ed00-d5a5-11eb-8dd7-b142876f8215.png)

Thank You

**Comment by martimy** [comment]
Can you send me the topology file so I can recreate the problem?

**Comment by c1x1x00xxPentium** [comment]
Dear Mr. Maen Artimy,
Here is my Mininet topology ...
Terminal Command :: `sudo python2 --custom --topo=mytopo ./Topo-1.py --controller=remote --arp`

Thanks

=TOPO_1===========================================
#!/usr/bin/python
from mininet.topo import Topo
from mininet.node import Host, OVSKernelSwitch
from mininet.link import TCLink

class MyLinearTopo( Topo ):
  "Linear topology script. (Note : No Router)"

  def build( self ):
    "Create custom topo."

    # Add hosts
    h1 = self.addHost('h1', mac='00:00:00:00:00:01', cls=Host,)
    h2 = self.addHost('h2', mac='00:00:00:00:00:02', cls=Host,)
    h3 = self.addHost('h3', mac='00:00:00:00:00:03', cls=Host,)
    h4 = self.addHost('h4', mac='00:00:00:00:00:04', cls=Host,)
    h5 = self.addHost('h5', mac='00:00:00:00:00:05', cls=Host,)
    h6 = self.addHost('h6', mac='00:00:00:00:00:06', cls=Host,)
    h7 = self.addHost('h7', mac='00:00:00:00:00:07', cls=Host,)
    h8 = self.addHost('h8', mac='00:00:00:00:00:08', cls=Host,)
    h9 = self.addHost('h9', mac='00:00:00:00:00:09', cls=Host,)
    h10 = self.addHost('h10', mac='00:00:00:00:00:0A', cls=Host,)
    h11 = self.addHost('h11', mac='00:00:00:00:00:0B', cls=Host,)
    h12 = self.addHost('h12', mac='00:00:00:00:00:0C', cls=Host,)
    h13 = self.addHost('h13', mac='00:00:00:00:00:0D', cls=Host,)
    h14 = self.addHost('h14', mac='00:00:00:00:00:0E', cls=Host,)
    h15 = self.addHost('h15', mac='00:00:00:00:00:0F', cls=Host,)
    h16 = self.addHost('h16', mac='00:00:00:00:00:10', cls=Host,)
    h17 = self.addHost('h17', mac='00:00:00:00:00:11', cls=Host,)
    h18 = self.addHost('h18', mac='00:00:00:00:00:12', cls=Host,)

    # Add switches    
    s1 = self.addSwitch('s1', cls=OVSKernelSwitch, protocols='OpenFlow13',)
    s2 = self.addSwitch('s2', cls=OVSKernelSwitch, protocols='OpenFlow13',)
    s3 = self.addSwitch('s3', cls=OVSKernelSwitch, protocols='OpenFlow13',)
    s4 = self.addSwitch('s4', cls=OVSKernelSwitch, protocols='OpenFlow13',)
    s5 = self.addSwitch('s5', cls=OVSKernelSwitch, protocols='OpenFlow13',)
    s6 = self.addSwitch('s6', cls=OVSKernelSwitch, protocols='OpenFlow13',)
    s7 = self.addSwitch('s7', cls=OVSKernelSwitch, protocols='OpenFlow13',)

    # Add links    
    # Switch-Switch
    self.addLink(s1, s3, port1=1, port2=1, cls=TCLink, bw=100,)
    self.addLink(s3, s2, port1=2, port2=1, cls=TCLink, bw=100,)
    self.addLink(s3, s4, port1=3, port2=1, cls=TCLink, bw=100,)
    self.addLink(s1, s6, port1=2, port2=1, cls=TCLink, bw=100,)
    self.addLink(s6, s5, port1=2, port2=1, cls=TCLink, bw=100,)
    self.addLink(s6, s7, port1=3, port2=1, cls=TCLink, bw=100,)

    # Host-Switch
    self.addLink(h1, s2, port1=1, port2=2, cls=TCLink, bw=100,)
    self.addLink(h2, s2, port1=1, port2=3, cls=TCLink, bw=100,)
    self.addLink(h3, s2, port1=1, port2=4, cls=TCLink, bw=100,)
    self.addLink(h4, s3, port1=1, port2=4, cls=TCLink, bw=100,)
    self.addLink(h5, s3, port1=1, port2=5, cls=TCLink, bw=100,)
    self.addLink(h6, s3, port1=1, port2=6, cls=TCLink, bw=100,)
    self.addLink(h7, s4, port1=1, port2=2, cls=TCLink, bw=100,)
    self.addLink(h8, s4, port1=1, port2=3, cls=TCLink, bw=100,)
    self.addLink(h9, s4, port1=1, port2=4, cls=TCLink, bw=100,)
    
    self.addLink(h10, s5, port1=1, port2=2, cls=TCLink, bw=100,)
    self.addLink(h11, s5, port1=1, port2=3, cls=TCLink, bw=100,)
    self.addLink(h12, s5, port1=1, port2=4, cls=TCLink, bw=100,)
    self.addLink(h13, s6, port1=1, port2=4, cls=TCLink, bw=100,)
    self.addLink(h14, s6, port1=1, port2=5, cls=TCLink, bw=100,)
    self.addLink(h15, s6, port1=1, port2=6, cls=TCLink, bw=100,)
    self.addLink(h16, s7, port1=1, port2=2, cls=TCLink, bw=100,)
    self.addLink(h17, s7, port1=1, port2=3, cls=TCLink, bw=100,)
    self.addLink(h18, s7, port1=1, port2=4, cls=TCLink, bw=100,)

topos = { 'mytopo': ( lambda: MyLinearTopo() ) }

=TOPO_2===========================================
#!/usr/bin/python
from mininet.topo import Topo
from mininet.node import Host, OVSKernelSwitch
from mininet.link import TCLink

class MyLinearTopo( Topo ):
  "Linear topology script. (Note : With Router)"

  def build( self ):
    "Create custom topo."

    # Add hosts
    # Host Service
    h1 = self.addHost('h1', mac='00:00:00:00:00:01', cls=Host, ip='172.16.1.1/24', defaultRoute='via 172.16.1.100')
    h2 = self.addHost('h2', mac='00:00:00:00:00:02', cls=Host, ip='172.16.1.2/24', defaultRoute='via 172.16.1.100')
    h3 = self.addHost('h3', mac='00:00:00:00:00:03', cls=Host, ip='172.16.1.3/24', defaultRoute='via 172.16.1.100')
    h4 = self.addHost('h4', mac='00:00:00:00:00:04', cls=Host, ip='172.16.1.4/24', defaultRoute='via 172.16.1.100')
    h5 = self.addHost('h5', mac='00:00:00:00:00:05', cls=Host, ip='172.16.1.5/24', defaultRoute='via 172.16.1.100')
    h6 = self.addHost('h6', mac='00:00:00:00:00:06', cls=Host, ip='172.16.1.6/24', defaultRoute='via 172.16.1.100')
    h7 = self.addHost('h7', mac='00:00:00:00:00:07', cls=Host, ip='172.16.1.7/24', defaultRoute='via 172.16.1.100')
    h8 = self.addHost('h8', mac='00:00:00:00:00:08', cls=Host, ip='172.16.1.8/24', defaultRoute='via 172.16.1.100')
    h9 = self.addHost('h9', mac='00:00:00:00:00:09', cls=Host, ip='172.16.1.9/24', defaultRoute='via 172.16.1.100')

    # Host Attacker
    h10 = self.addHost('h10', mac='00:00:00:00:00:0A', cls=Host, ip='172.16.2.1/24', defaultRoute='via 172.16.2.100')
    h11 = self.addHost('h11', mac='00:00:00:00:00:0B', cls=Host, ip='172.16.2.2/24', defaultRoute='via 172.16.2.100')
    h12 = self.addHost('h12', mac='00:00:00:00:00:0C', cls=Host, ip='172.16.2.3/24', defaultRoute='via 172.16.2.100')
    h13 = self.addHost('h13', mac='00:00:00:00:00:0D', cls=Host, ip='172.16.2.4/24', defaultRoute='via 172.16.2.100')
    h14 = self.addHost('h14', mac='00:00:00:00:00:0E', cls=Host, ip='172.16.2.5/24', defaultRoute='via 172.16.2.100')
    h15 = self.addHost('h15', mac='00:00:00:00:00:0F', cls=Host, ip='172.16.2.6/24', defaultRoute='via 172.16.2.100')
    h16 = self.addHost('h16', mac='00:00:00:00:00:10', cls=Host, ip='172.16.2.7/24', defaultRoute='via 172.16.2.100')
    h17 = self.addHost('h17', mac='00:00:00:00:00:11', cls=Host, ip='172.16.2.8/24', defaultRoute='via 172.16.2.100')
    h18 = self.addHost('h18', mac='00:00:00:00:00:12', cls=Host, ip='172.16.2.9/24', defaultRoute='via 172.16.2.100')

    # Add switches    
    s1 = self.addSwitch('s1', cls=OVSKernelSwitch, protocols='OpenFlow13', defaultRoute='via 10.10.10.2') # Router Service
    s2 = self.addSwitch('s2', cls=OVSKernelSwitch, protocols='OpenFlow13', defaultRoute='via 10.10.10.1') # Router Attacker
    s3 = self.addSwitch('s3', cls=OVSKernelSwitch, protocols='OpenFlow13',)
    s4 = self.addSwitch('s4', cls=OVSKernelSwitch, protocols='OpenFlow13',)
    s5 = self.addSwitch('s5', cls=OVSKernelSwitch, protocols='OpenFlow13',)
    s6 = self.addSwitch('s6', cls=OVSKernelSwitch, protocols='OpenFlow13',)
    s7 = self.addSwitch('s7', cls=OVSKernelSwitch, protocols='OpenFlow13',)
    s8 = self.addSwitch('s8', cls=OVSKernelSwitch, protocols='OpenFlow13',)

    # Add links    
    # Switch-Switch
    self.addLink(s1, s2, port1=1, port2=1, cls=TCLink, bw=100, params1={'ip' : '10.10.10.1/30'}, params2={ 'ip' : '10.10.10.2/30' } ) 
    
    self.addLink(s1, s4, port1=2, port2=1, cls=TCLink, bw=100, params1={'ip' : '172.16.1.100/24'}, )
    self.addLink(s4, s3, port1=2, port2=1, cls=TCLink, bw=100,)
    self.addLink(s4, s5, port1=3, port2=1, cls=TCLink, bw=100,)
    
    self.addLink(s2, s7, port1=2, port2=1, cls=TCLink, bw=100, params1={'ip' : '172.16.2.100/24'})
    self.addLink(s7, s6, port1=2, port2=1, cls=TCLink, bw=100,)
    self.addLink(s7, s8, port1=3, port2=1, cls=TCLink, bw=100,)

    # Host-Switch
    self.addLink(h1, s3, port1=1, port2=2, cls=TCLink, bw=100,)
    self.addLink(h2, s3, port1=1, port2=3, cls=TCLink, bw=100,)
    self.addLink(h3, s3, port1=1, port2=4, cls=TCLink, bw=100,)

    self.addLink(h4, s4, port1=1, port2=4, cls=TCLink, bw=100,)
    self.addLink(h5, s4, port1=1, port2=5, cls=TCLink, bw=100,)
    self.addLink(h6, s4, port1=1, port2=6, cls=TCLink, bw=100,)

    self.addLink(h7, s5, port1=1, port2=2, cls=TCLink, bw=100,)
    self.addLink(h8, s5, port1=1, port2=3, cls=TCLink, bw=100,)
    self.addLink(h9, s5, port1=1, port2=4, cls=TCLink, bw=100,)
    # -----------------
    self.addLink(h10, s6, port1=1, port2=2, cls=TCLink, bw=100,)
    self.addLink(h11, s6, port1=1, port2=3, cls=TCLink, bw=100,)
    self.addLink(h12, s6, port1=1, port2=4, cls=TCLink, bw=100,)

    self.addLink(h13, s7, port1=1, port2=4, cls=TCLink, bw=100,)
    self.addLink(h14, s7, port1=1, port2=5, cls=TCLink, bw=100,)
    self.addLink(h15, s7, port1=1, port2=6, cls=TCLink, bw=100,)

    self.addLink(h16, s8, port1=1, port2=2, cls=TCLink, bw=100,)
    self.addLink(h17, s8, port1=1, port2=3, cls=TCLink, bw=100,)
    self.addLink(h18, s8, port1=1, port2=4, cls=TCLink, bw=100,)

topos = { 'mytopo': ( lambda: MyLinearTopo() ) }

=TOPO_3===========================================
#!/usr/bin/python
from mininet.topo import Topo
from mininet.node import Host, OVSKernelSwitch
from mininet.link import TCLink

class MyTreeTopo( Topo ): # Tree topology script

  def build( self ):
    "Create custom topo. (Note : No Router)"

    # Add hosts
    h1 = self.addHost('h1', mac='00:00:00:00:01:00', cls=Host,)
    h2 = self.addHost('h2', mac='00:00:00:00:02:00', cls=Host,)
    h3 = self.addHost('h3', mac='00:00:00:00:03:00', cls=Host,)
    h4 = self.addHost('h4', mac='00:00:00:00:04:00', cls=Host,)
    h5 = self.addHost('h5', mac='00:00:00:00:05:00', cls=Host,)
    h6 = self.addHost('h6', mac='00:00:00:00:06:00', cls=Host,)
    h7 = self.addHost('h7', mac='00:00:00:00:07:00', cls=Host,)
    h8 = self.addHost('h8', mac='00:00:00:00:08:00', cls=Host,)
    h9 = self.addHost('h9', mac='00:00:00:00:09:00', cls=Host,)
    h10 = self.addHost('h10', mac='00:00:00:00:0A:00', cls=Host,)
    h11 = self.addHost('h11', mac='00:00:00:00:0B:00', cls=Host,)
    h12 = self.addHost('h12', mac='00:00:00:00:0C:00', cls=Host,)
    h13 = self.addHost('h13', mac='00:00:00:00:0D:00', cls=Host,)
    h14 = self.addHost('h14', mac='00:00:00:00:0E:00', cls=Host,)
    h15 = self.addHost('h15', mac='00:00:00:00:0F:00', cls=Host,)
    h16 = self.addHost('h16', mac='00:00:00:00:10:00', cls=Host,)
    h17 = self.addHost('h17', mac='00:00:00:00:11:00', cls=Host,)
    h18 = self.addHost('h18', mac='00:00:00:00:12:00', cls=Host,)
    h19 = self.addHost('h19', mac='00:00:00:00:13:00', cls=Host,)
    h20 = self.addHost('h20', mac='00:00:00:00:14:00', cls=Host,)
    h21 = self.addHost('h21', mac='00:00:00:00:15:00', cls=Host,)
    h22 = self.addHost('h22', mac='00:00:00:00:16:00', cls=Host,)
    h23 = self.addHost('h23', mac='00:00:00:00:17:00', cls=Host,)
    h24 = self.addHost('h24', mac='00:00:00:00:18:00', cls=Host,)

    # Add switches    
    s1 = self.addSwitch('s1', cls=OVSKernelSwitch, protocols='OpenFlow13',)
    s2 = self.addSwitch('s2', cls=OVSKernelSwitch, protocols='OpenFlow13',)
    s3 = self.addSwitch('s3', cls=OVSKernelSwitch, protocols='OpenFlow13',)
    s4 = self.addSwitch('s4', cls=OVSKernelSwitch, protocols='OpenFlow13',)
    s5 = self.addSwitch('s5', cls=OVSKernelSwitch, protocols='OpenFlow13',)
    s6 = self.addSwitch('s6', cls=OVSKernelSwitch, protocols='OpenFlow13',)
    s7 = self.addSwitch('s7', cls=OVSKernelSwitch, protocols='OpenFlow13',)
    s8 = self.addSwitch('s8', cls=OVSKernelSwitch, protocols='OpenFlow13',)
    s9 = self.addSwitch('s9', cls=OVSKernelSwitch, protocols='OpenFlow13',)
    s10 = self.addSwitch('s10', cls=OVSKernelSwitch, protocols='OpenFlow13',)
    s11 = self.addSwitch('s11', cls=OVSKernelSwitch, protocols='OpenFlow13',)
    s12 = self.addSwitch('s12', cls=OVSKernelSwitch, protocols='OpenFlow13',)
    s13 = self.addSwitch('s13', cls=OVSKernelSwitch, protocols='OpenFlow13',)

    # Switch-Switch
    self.addLink(s1, s2, port1=1, port2=1, cls=TCLink, bw=100,)
    self.addLink(s1, s3, port1=2, port2=1, cls=TCLink, bw=100,)
    self.addLink(s2, s4, port1=2, port2=1, cls=TCLink, bw=100,)
    self.addLink(s2, s5, port1=3, port2=1, cls=TCLink, bw=100,)
    self.addLink(s3, s6, port1=2, port2=1, cls=TCLink, bw=100,)
    self.addLink(s3, s7, port1=3, port2=1, cls=TCLink, bw=100,)
    
    self.addLink(s1, s8, port1=3, port2=1, cls=TCLink, bw=100,)
    self.addLink(s1, s9, port1=4, port2=1, cls=TCLink, bw=100,)
    self.addLink(s8, s10, port1=2, port2=1, cls=TCLink, bw=100,)
    self.addLink(s8, s11, port1=3, port2=1, cls=TCLink, bw=100,)
    self.addLink(s9, s12, port1=2, port2=1, cls=TCLink, bw=100,)
    self.addLink(s9, s13, port1=3, port2=1, cls=TCLink, bw=100,)

    # Host-Switch
    self.addLink(h1, s4, port1=1, port2=2, cls=TCLink, bw=100,)
    self.addLink(h2, s4, port1=1, port2=3, cls=TCLink, bw=100,)
    self.addLink(h3, s4, port1=1, port2=4, cls=TCLink, bw=100,)
    self.addLink(h4, s5, port1=1, port2=2, cls=TCLink, bw=100,)
    self.addLink(h5, s5, port1=1, port2=3, cls=TCLink, bw=100,)
    self.addLink(h6, s5, port1=1, port2=4, cls=TCLink, bw=100,)
    self.addLink(h7, s6, port1=1, port2=2, cls=TCLink, bw=100,)
    self.addLink(h8, s6, port1=1, port2=3, cls=TCLink, bw=100,)
    self.addLink(h9, s6, port1=1, port2=4, cls=TCLink, bw=100,)
    self.addLink(h10, s7, port1=1, port2=2, cls=TCLink, bw=100,)
    self.addLink(h11, s7, port1=1, port2=3, cls=TCLink, bw=100,)
    self.addLink(h12, s7, port1=1, port2=4, cls=TCLink, bw=100,)
    # ----------
    self.addLink(h13, s10, port1=1, port2=2, cls=TCLink, bw=100,)
    self.addLink(h14, s10, port1=1, port2=3, cls=TCLink, bw=100,)
    self.addLink(h15, s10, port1=1, port2=4, cls=TCLink, bw=100,)
    self.addLink(h16, s11, port1=1, port2=2, cls=TCLink, bw=100,)
    self.addLink(h17, s11, port1=1, port2=3, cls=TCLink, bw=100,)
    self.addLink(h18, s11, port1=1, port2=4, cls=TCLink, bw=100,)
    self.addLink(h19, s12, port1=1, port2=2, cls=TCLink, bw=100,)
    self.addLink(h20, s12, port1=1, port2=3, cls=TCLink, bw=100,)
    self.addLink(h21, s12, port1=1, port2=4, cls=TCLink, bw=100,)
    self.addLink(h22, s13, port1=1, port2=2, cls=TCLink, bw=100,)
    self.addLink(h23, s13, port1=1, port2=3, cls=TCLink, bw=100,)
    self.addLink(h24, s13, port1=1, port2=4, cls=TCLink, bw=100,)

topos = { 'mytopo': ( lambda: MyTreeTopo() ) }

**Comment by martimy** [comment]
![Topo1](https://user-images.githubusercontent.com/4184429/123820819-4017d400-d8d1-11eb-9ced-6d57ffa80117.PNG)
![Topo2](https://user-images.githubusercontent.com/4184429/123820833-43ab5b00-d8d1-11eb-981d-32b7febf2822.PNG)
![Topo3](https://user-images.githubusercontent.com/4184429/123820844-45751e80-d8d1-11eb-9836-8de30bd8ad46.PNG)

**Comment by martimy** [comment]
I could not replicate the problem (because  I don't have the code you used), but I noticed you used Python2. The code was written in Python3 and I used the following commands:

To run Mininet:
sudo mn --custom TopoTest.py --topo mytopo --switch ovs --controller remote

To run controller and applications:
ryu-manager ryu.app.simple_switch_13 flowmanager/flowmanager.py --observe-links

Notice --observe-link enables LLDP, which is needed to create the topology correctly as you can see from previous comment.

Have you used Python3 to run FlowManager?

**Comment by c1x1x00xxPentium** [comment]
Dear Mr. Maen Artimy,

I am realized that I forgot to use `--observe-links` to run ryu-manager, and now my topology looks well.
After that as you asked me about how I use the FlowManager, I am using on Python3.8 ...

Beside that, can you give me any advice how to resolve the "Log Message Page", i am still confused how to make it work. Also about "Snort Log Alert Message".

Note : That was correct, my terminal command to run Mininet was wrong, thank you for your info.

Thank You

**Comment by martimy** [comment]
Hi,
Unfortunately, I cannot replicate the error message without the code that caused it.

For Snort, here is part of code that may help: 

DOS and LEAK are strings that are including in your SNORT Alert message.

```    
    # Event Handlers
    @set_ev_cls(snortlib.EventAlert, MAIN_DISPATCHER)
    def process_alert(self, ev):
        msg = ev.msg

        alertmsg = msg.alertmsg[0].decode('ascii')
        print(f'alertmsg: {alertmsg}')

        pkt = packet.Packet(array.array('B', msg.pkt))
        protocol_list = dict((p.protocol_name, p)
                      for p in pkt.protocols
                      if isinstance(p, packet_base.PacketBase))

        if DOS in alertmsg:
            self.block_dos(pkt, protocol_list)
        if LEAK in alertmsg:
            self.block_leak(pkt, protocol_list)

```
